name: Build and Run .NET Framework Console App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # manual trigger

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup MSBuild (comes preinstalled on windows-latest)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # Restore packages
      - name: Restore NuGet packages
        run: nuget restore AsyncAwaitTask.sln

      # Build project
      - name: Build with MSBuild
        run: msbuild AsyncAwaitTask.sln /p:Configuration=Release

      # Run Console App
      - name: Run Console App
        run: |
          cd AsyncAwaitTask\bin\Release
          .\AsyncAwaitTask.exe
